refs #12766 Simplifies Exception hierarchy and handling
os-nsu/ostest-back pull request #26
Opened 2024-10-22 14:11 UTC by nastyasteshchenko

2024-10-29 16:07 UTC, brusN requested changes

2024-10-29 16:07 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/LaboratoryService.java
> +            throw new DuplicateKeyException(String.format("Laboratory with name '%s' already exists", name));
Аналогично предыдущему комменту

2024-10-29 16:07 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/RoleService.java
> +            throw new EntityNotFoundException("Couldn't find role " + name);
Аналогично предыдущему замечанию

2024-10-29 16:07 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/UserService.java
> +                () -> new EntityNotFoundException("Couldn't find user with id: " + id));
Аналогично предыдущему замечанию

2024-10-29 16:10 UTC, brusN commented
Крч, я устал писать - повсеместно в коде одно и то же большое замечание. Не нужно использовать исключения со сторонних либ - лучше разработать свою архитектуру. 

1. Свои же исключения можно расширять, чтобы они могли нести в себе дополнительную информацию
2. Ты можешь выстроить свою иерархию. Например, крупноблочно - DomainException - главное исключение, наследуемое от RuntimeException. Далее все исключения наследуются от него, например, AuthorizationException и ValidationException, от него идут WrongPasswordException, UserNotFoundException и т.д.. Думаю, суть ясна. Как минимум, можно ловить DomainException - и ты уже перехватываешь все свои исключения и ограничиваешь область обработки, если не хочешь ловить Throwable или Exception.
3. Ты не знаешь контекст "чужих" исключений, название не факт что соответствует действительности.
4. Ты можешь отлавливать ненужные тебе исключения во время работы той же либы.

2024-10-29 16:17 UTC, brusN commented
Переделывать почти все, а фронту надо двигаться - логику, необходимую для сдвига фронта, вынеси в отдельные коммиты ну или че нить сделай, что не стопорить людей тада

2024-10-30 12:13 UTC, nastyasteshchenko commented
Можно смотреть

2024-11-07 16:47 UTC, brusN commented
PR тяжко смотреть, когда в него намешан код с других PRов. Посмотрел как смог просто код репы. Что увидел - суть по иерархии ты уловила, но не до конца.

1. Местами есть лишняя иерархия. Явные пример: `UserNotFoundException -> NotFoundException -> ValidationException`.
`NotFoundException` кроме иерархии у тебя нигде не фигугирует, да вообще незачем абстрагировать настолько. `UserNotFoundException -> ValidationException` вполне достаточно. `DuplicateNameException` та же история.

2. Также я не увидел "генерального нашего исключения", от которого идут наши более конкретные, но все еще базовые исключения по типу `ValidationException`.

3. `NoRightsException` наследуешь от `RuntimeException` - не логично его к `AuthorizationException` отнести?

2024-11-07 16:47 UTC, brusN requested changes

2024-11-07 16:47 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/GroupService.java
> +            log.error(DUPLICATED_NAME_MESSAGE);
Этот лог практически аналогичен сообщению в самом exception - он вообще незачем. Причем по коду много таких мест, но я не буду в каждом писать. Давай делать лог вместе с бросанием exception только если он отличается или "заметно уточняет". А так - пусть exception ловит контроллер и в нем же логирует ошибку.

2024-11-07 16:48 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/GroupService.java
> +            log.error(DUPLICATED_NAME_MESSAGE);
p.s. переделываем все аналогичные места

2024-11-10 13:52 UTC, brusN requested changes

2024-11-10 13:52 UTC, brusN commented on src/main/java/ru/nsu/ostest/adapter/in/rest/exception/RestExceptionHandler.java
>  @RestControllerAdvice
Добавь обработку DomainException. Отдельные генеральные исключения, которые наследуются от него, мы уже добавили в ExceptionHadler, теперь надо добавить "на всякий случай" обработку DomainException. Пусть ошибка будет принадлежать к группе 5хх - ошибка сервера

2024-11-10 16:21 UTC, brusN approved these changes

2024-11-10 18:00 UTC, merged