refs #12641 Added logout request
os-nsu/ostest-back pull request #28
Opened 2024-10-26 09:01 UTC by Just0Lina

refs #12641 Added logout request

2024-10-29 12:13 UTC, brusN commented on src/main/java/ru/nsu/ostest/security/impl/JwtProviderImpl.java
> +                           @Value("${jwt.secret.refresh}") String jwtRefreshSecret, BlacklistService blacklistService) {
minor: перенеси аргумент `BlacklistService blacklistService` на следующую строку, не надо колбаску длинную лепить, тем более он вышел за допуск по количеству символов

2024-10-29 12:14 UTC, brusN commented on src/main/java/ru/nsu/ostest/security/impl/JwtProviderImpl.java
> +            log.error("Token is blacklisted");
Где-то в константы выносила, тут просто литералом. Нету единообразия. Ну это так - опять повонять на эту тему, не более

2024-10-29 12:21 UTC, brusN commented on src/main/java/ru/nsu/ostest/security/impl/BlacklistService.java
> +    private final ConcurrentHashMap<String, Long> tokenBlacklist = new ConcurrentHashMap<>();
1. А чем обусловлен выбор ConcurrentHashMap? У тебя в AuthServiceImpl обычный HashMap, в оба пишутся изменения в одном месте (мне интересно, пока ничего не меняй)
2. Надо интерфейс указывать в типе, а не реализацию

2024-10-29 12:27 UTC, brusN commented on src/main/java/ru/nsu/ostest/security/impl/AuthServiceImpl.java
> +        refreshStorage.remove(userId);
Я правильно понимаю, что в принципе если чел заходит с разных устройств, то он взаимодействует с одинаковыми токенами, а при logout на одном устройстве мы грохаем все сессии на других заодно?

2024-10-29 12:35 UTC, brusN commented on src/test/java/ru/nsu/ostest/user/UserControllerIntegrationTest.java
> +        verify(authService).logout(request);
На будущее - во всем классе тестируется логика по сути для сервиса, а не для контроллера - контроллер незачем тестировать, он и так простой. Логично бы в целом тест-класс под сервис было завести, но пофиг. Поэтому этот `verify()` выглядит лишним.

2024-10-29 12:36 UTC, brusN commented on src/test/java/ru/nsu/ostest/user/UserControllerIntegrationTest.java
> +    @Test
Не хватает теста для негативного сценария

2024-10-29 12:40 UTC, brusN commented
Отпишусь, что не было цели "засрать" - я особо в репу до сегодня не смотрел, сегодня по разбирался и у меня батхерт от некоторых решений, которые в итоге в прод пошли. Но опять же - это всего лишь мое мнение, а тимлид по бэку - Рома

2024-11-04 04:56 UTC, Just0Lina commented on src/main/java/ru/nsu/ostest/security/impl/AuthServiceImpl.java
> +        refreshStorage.remove(userId);
Да, так и происходит. Токены же невалидные становятся

2024-11-04 05:36 UTC, Just0Lina commented on src/main/java/ru/nsu/ostest/security/impl/BlacklistService.java
> +    private final ConcurrentHashMap<String, Long> tokenBlacklist = new ConcurrentHashMap<>();
Подумала, что логично кидать в потокобезопасную мапу, если много клиентов захотят выйти одновременно, например.

2024-11-04 16:40 UTC, brusN commented on src/main/java/ru/nsu/ostest/security/impl/AuthServiceImpl.java
> +        refreshStorage.remove(userId);
Ну, не сказать что так правильно, да и х с ним)

2024-11-04 17:06 UTC, brusN commented on src/test/java/ru/nsu/ostest/user/AuthServiceUnitTest.java
> +        verify(blacklistService, times(1)).addToBlacklist(validAccessToken);
minor: можно еще добавить проверку на вызов `refreshStorage.remove(userId);` и/или что действительно убрали токен из хранилища. Для второго теста аналогично наоборот.

2024-11-04 17:06 UTC, brusN commented on src/test/java/ru/nsu/ostest/user/AuthServiceUnitTest.java
> +        Exception exception = assertThrows(Exception.class, () -> {
То что проверили на генерацию исключения - гуд, но не гуд, что обобщили (если метод действительно не выбрасывает Exception). В `assertThrows` указывай то исключение, которое должно быть брошено. 

Вне контекста: так ты можешь перехватить другое исключение и в некоторых случаях тест может проходить, хотя написан неправильно

2024-11-04 17:14 UTC, brusN commented on src/main/java/ru/nsu/ostest/security/impl/BlacklistService.java
> +    private final ConcurrentHashMap<String, Long> tokenBlacklist = new ConcurrentHashMap<>();
Да, это правильно. Но у тебя в одном месте идет взаимодействие с двумя структурами данных - одна потокобезопасна, вторая нет. 

Я к тому, что в `AuthServiceImpl` нужно тоже потокобезопасную

@yattroman я же прав?)

2024-11-04 17:46 UTC, yattroman requested changes

2024-11-04 17:46 UTC, yattroman commented on src/main/java/ru/nsu/ostest/security/impl/BlacklistService.java
> +    private final ConcurrentHashMap<String, Long> tokenBlacklist = new ConcurrentHashMap<>();
Да, го докинем ConcurrentHashMap в AuthServiceImpl

2024-11-07 16:22 UTC, brusN approved these changes

2024-11-07 16:25 UTC, yattroman approved these changes

2024-11-07 16:28 UTC, merged