refs #12642 #12730 Added base user filtering
os-nsu/ostest-back pull request #35
Opened 2024-11-12 12:49 UTC by Just0Lina

2024-11-18 18:12 UTC, brusN commented on src/main/java/ru/nsu/ostest/adapter/in/rest/model/filter/SearchRequestDto.java
> +            pagination = new Pagination(1, 20, null, null);
minor: как вариант, у Pagination статик метод .getDefaultInstance() или чето такое

2024-11-18 18:18 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/GroupService.java
> +    private static final String GROUP_NOT_FOUND_MESSAGE_TEMPLATE = "Group not found.";
Обе константы нигде не используются - зачем они нужны?

2024-11-18 18:18 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/GroupService.java
>      private final UserMapper userMapper;
Тоже не используется в классе

2024-11-18 18:21 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/IntegerFilterStrategy.java
> +            @SuppressWarnings("unchecked")
Обязательно добавляй поясняющий коммент зачем ты подавляешь warning`и. И вообще, лучше решать по-нормальному и только в крайнем случае пользоваться "глушилкой". Тут точно по-другому нельзя?

2024-11-18 18:30 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/UserService.java
> +                getFieldDescriptors(User.class),
Можно сделать что-то типа UserMetaProvider и либо синглтон, либо статик контекст, но один раз вызываешь  `getFieldDescriptors()`, `getFilterDescriptors()` в конструкторе/static {}, в нем кэшируешь (просто хранишь) и при необходимости вызываешь геттеры. Таким образом, не будешь каждый раз вычислять

2024-11-19 08:26 UTC, Just0Lina commented on src/main/java/ru/nsu/ostest/domain/service/GroupService.java
>      private final UserMapper userMapper;
Эти констатны с ребейзом приехали, в первый раз вижу, удалю или найду...

2024-11-19 18:57 UTC, brusN requested changes

2024-11-19 18:57 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/MetaProvider.java
> +    private static final Map<Class<?>, List<FieldDescriptor>> fieldDescriptorsCache = new ConcurrentHashMap<>();
не вижу смысла в ConcurrentHashMap здесь, почему ты его здесь используешь?

2024-11-19 18:57 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/MetaProvider.java
> +    private static final Map<Class<?>, List<FieldDescriptor>> fieldDescriptorsCache = new ConcurrentHashMap<>();
в принципе не вижу смысла в мапе, провайдер можно было завести отдельно для каждого класса и в статическом блоке вычислять наш кэш

2024-11-20 19:33 UTC, brusN approved these changes

2024-11-21 05:04 UTC, merged