refs #13394 Added attempt results
os-nsu/ostest-back pull request #38
Opened 2024-11-12 19:00 UTC by Just0Lina

2024-11-13 15:16 UTC, yattroman requested changes

2024-11-13 15:16 UTC, yattroman commented on src/main/java/ru/nsu/ostest/adapter/out/persistence/entity/session/AttemptResults.java
> +    @ManyToOne
Давай OneToOne

2024-11-18 09:15 UTC, Just0Lina commented on src/main/java/ru/nsu/ostest/domain/service/AttemptService.java
> +    public AttemptResultSetResponse saveAttemptResult(AttemptResultSetRequest request) {
Проставила статусы как и для попытки, типа успех или нет

2024-11-18 14:29 UTC, yattroman commented on src/main/java/ru/nsu/ostest/adapter/in/rest/model/session/AttemptDto.java
> +        AttemptResultDto attemptResultDto
Можно убрать суффикс dto

2024-11-18 14:32 UTC, yattroman commented on src/main/java/ru/nsu/ostest/domain/service/AttemptService.java
> +        attempt.setAttemptResults(attemptResults);
Го вынесем добавление attemptResults в attempt - тип setResults()

2024-11-18 14:35 UTC, yattroman commented on src/main/resources/db/changelog/db.changelog-master.xml
> +    <include file="/db/changelog/2024/11/12-01-changelog.xml"/>
Убери слеши спереди пж

2024-11-18 14:56 UTC, yattroman approved these changes

2024-11-18 17:33 UTC, closed without merging