refs #13990 The first series of BE fixing
os-nsu/ostest-back pull request #46
Opened 2024-12-08 08:46 UTC by nastyasteshchenko

2024-12-09 11:50 UTC, yattroman requested changes

2024-12-09 11:50 UTC, yattroman commented on src/test/java/ru/nsu/ostest/task/TasksSchedulerTest.java
> +    public void testCheckAttemptTimeoutsChangesStatus() throws InterruptedException {
А вот тут можно попробовать сохранить Attempt через repository? Чтоб без моков. Тогда будто бы и тест БД не нужно толком)))
И попробовать время создания самим установить тоже

2024-12-16 14:22 UTC, yattroman commented on src/main/java/ru/nsu/ostest/adapter/out/persistence/entity/session/Attempt.java
> +    @PostLoad
А зачем?

2024-12-16 14:31 UTC, nastyasteshchenko commented on src/main/java/ru/nsu/ostest/adapter/out/persistence/entity/session/Attempt.java
> +    @PostLoad
криво работало, так как createAt сохраняет без определенной таймзоны, сделала вот такое, ибо не знала как что еще исправить

2024-12-16 14:44 UTC, yattroman commented on src/main/java/ru/nsu/ostest/adapter/out/persistence/entity/session/Attempt.java
> +    @PostLoad
оки, потом можно будет переделать

2024-12-18 05:55 UTC, yattroman approved these changes

2024-12-18 06:35 UTC, merged