refs#12195-crud без ролей
os-nsu/ostest-back pull request #9
Opened 2024-10-03 13:31 UTC by MariiaKataeva

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/adapter/in/rest/controller/TestController.java
> +    public ResponseEntity<TestDto> getTest(@PathVariable Long id) {
Давай без ResponseEntity - подсмотри, как по лабораторным сделано

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/adapter/in/rest/controller/TestController.java
> +        if (file.isEmpty()) {
Вот это бы в сервисе держать)
Но вообще, я бы сделал файл опциональным - если что, потом подкинут. А ResponseEntity возвращать не нада - лучше просто исключение выкинуть, а потом его обработать в handler

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +        if (testRepository.findByName(test.getName()) != null) {
Вот тут можешь подсмотреть, как сделано у Насти с лапами

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +    public Long create(TestDto testDto, byte[] script) {
А вот тут я бы принимал всё-таки TestCreationDto и скрипт, а потом проводил с ним манипуляции

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +        Test test = testRepository.findById(id).orElse(null);
тут можно orElseThrow тогда

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +        for (Test t : tests) {
Давай мапперу скормим, он сам сообразит. Просто ему надо метод определить.

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +    public Long update(TestDto testDto, byte[] script) {
Ну вот тут сомнительное обновление) Давай существующей сущности просто поля обновим через маппер

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +        } catch (Exception e) {//todo: конкретизировать исключения
Убрал бы из try-catch

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +            return testRepository.save(test).getId();
Тут бы тоже убрал из try-catch

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +    public Long create(TestDto testDto, byte[] script) {
Мб как раз вернём testDto без скрипта?

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/adapter/in/rest/controller/TestController.java
> +            @RequestPart("data") TestCreationRequestDto request,
Ну нам нужна другая dto)

2024-10-03 14:22 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/adapter/in/rest/controller/TestController.java
> +        if (file.isEmpty()) {
Аналогично, как в создании

2024-10-04 06:29 UTC, brusN requested changes

2024-10-04 06:29 UTC, brusN commented on src/main/java/ru/nsu/ostest/adapter/in/rest/controller/TestController.java
> +            script = file.getBytes();
Логику доставания байтов из файла вынеси в отдельный private-метод отдельного сервиса, который принимает от контроллера данные на обработку, в т.ч. все исключения по ним. 

По типу:

```java
private static byte[] getBytesFromFile(...)
```

2024-10-04 06:29 UTC, brusN commented on src/main/java/ru/nsu/ostest/adapter/in/rest/exception/RestExceptionHandler.java
> +        return new ResponseEntity<>(Error.builder().code(404).message(e.getMessage()).build(), HttpStatus.BAD_REQUEST);
Литералы лучше вынести в константы, давай везде заменим

2024-10-04 06:29 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +            throw new NotFoundException("Test with the given id not found.");
Раз сообщения на русском делали, то давай и тут

2024-10-04 06:29 UTC, brusN commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +            throw new RuntimeException("Ошибка при сохранении данных." + e.getMessage());
Рома говорит, что "не надо русский" - перепиши сообщения экспешенов на англ

2024-10-05 03:44 UTC, MariiaKataeva commented
готово к cr

2024-10-06 04:43 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +        Test updatedTest
Вот тут что неразбериха какая-то тока

2024-10-06 04:47 UTC, Yattroman commented on src/main/java/ru/nsu/ostest/domain/service/TestService.java
> +        Test updatedTest
Тут короче, в mapper метод можно закинуть энтити, которую получили через findById, и dto для изменения. По сути, там потом перетекут изменения с dto на энтити, в коде по лабораторным можно также сделать

2024-10-06 04:47 UTC, Yattroman approved these changes

2024-10-07 14:58 UTC, Yattroman commented
Ребейзнись пж
И добавь тестов по аналогии с лабораторными

2024-10-10 12:18 UTC, yattroman commented on src/test/java/ru/nsu/ostest/test/TestControllerIntegrationTest.java
Вот первые 2 теста огонь, а остальные надо поправить аналогично. Глянь, как там Настя делала. Мб просто не увидела обновления) Но там все тесты однородные. Я бы ещё TestTestSetup перенес в LaboratoryTestSetup

2024-10-10 14:03 UTC, brusN approved these changes

2024-10-10 14:06 UTC, merged